INFO	| 2021-12-15 23:12:19,594	| DockbarX 0.93
INFO	| 2021-12-15 23:12:19,595	| DockbarX init
INFO	| 2021-12-15 23:12:19,899	| DockbarX reload
INFO	| 2021-12-15 23:16:04,596	| Executing: thunar 
ERROR	| 2021-12-15 23:21:47,656	| Traceback (most recent call last):
ERROR	| 2021-12-15 23:21:47,657	|   File "/usr/share/xfce4/panel/plugins/xfce4-dockbarx-plug", line 166, in image_pattern
ERROR	| 2021-12-15 23:21:47,657	|     surface = cairo.ImageSurface.create_from_png(image)
ERROR	| 2021-12-15 23:21:47,658	| Error: file not found
DEBUG	| 2021-12-15 23:21:47,658	| Failed to load image.
INFO	| 2021-12-15 23:21:53,745	| Executing: thunar 
INFO	| 2021-12-15 23:22:14,677	| DockbarX reload
INFO	| 2021-12-15 23:23:09,608	| Executing: firefox 
ERROR	| 2021-12-15 23:29:15,503	| Restarting DockManager Helpers failed.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dockbarx/dockmanager.py", line 142, in reset
    "/net/launchpad/DockManager/Daemon")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name net.launchpad.DockManager.Daemon was not provided by any .service files
INFO	| 2021-12-15 23:55:47,331	| Executing: thunar 
