INFO	| 2021-12-18 01:06:33,688	| DockbarX 0.93
INFO	| 2021-12-18 01:06:33,689	| DockbarX init
INFO	| 2021-12-18 01:06:35,029	| DockbarX reload
ERROR	| 2021-12-18 01:06:36,097	| Restarting DockManager Helpers failed.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dockbarx/dockmanager.py", line 142, in reset
    "/net/launchpad/DockManager/Daemon")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name net.launchpad.DockManager.Daemon was not provided by any .service files
INFO	| 2021-12-18 01:15:24,081	| Executing: thunar 
ERROR	| 2021-12-18 01:16:02,286	| /usr/lib/python2.7/dist-packages/dockbarx/windowbutton.py:194: Warning: Source ID 2962 was not found when attempting to remove it
  gobject.source_remove(self.item.deopacify_sid)
ERROR	| 2021-12-18 01:16:02,914	| /usr/lib/python2.7/dist-packages/dockbarx/windowbutton.py:194: Warning: Source ID 3275 was not found when attempting to remove it
  gobject.source_remove(self.item.deopacify_sid)
ERROR	| 2021-12-18 01:16:04,910	| /usr/lib/python2.7/dist-packages/dockbarx/windowbutton.py:360: Warning: Source ID 3820 was not found when attempting to remove it
  gobject.source_remove(self.opacify_sid)
